<?php
if ($header)
    echo $header;
if (isset($content1))
    echo $content1;
if (isset($panelUser1))
    echo $panelUser1;
if (isset($panelPassenger1))
    echo $panelPassenger1;
if (isset($panelAdmin1))
    echo $panelAdmin1;
if ($middle)
    echo $middle;
if (isset($panelUser2))
    echo $panelUser2;
if (isset($panelPassenger2))
    echo $panelPassenger2;
if (isset($panelAdmin2))
    echo $panelAdmin2;
if (isset($content2))
    echo $content2;
if ($footer)
    echo $footer;